### ISSUE TITLE
New CO2SYS version

### ISSUE THREAD

**Issue by simenbootsma** [HCBScienceProducts/CANYON-B#1]
As of February 2021, a new version of CO2SYS is available [here](https://github.com/jonathansharp/CO2-System-Extd). This version requires 4 additional parameters: NH<sub>4</sub>, H<sub>2</sub>S, KFCONSTANT, BORON. It would be great to have CANYON-B working with this version as well!

**Comment by HCBScienceProducts** [comment]
CO2SYS v2 is used in the internals of CANYON-B to convert pCO2 back from its form used in the neural networks to a real world pCO2 value. This was done to easily implement an error function that scales approx. with the relative error on pCO2, not the absolute error, for the neural network trainings. As such, CO2SYS for CANYON-B needs to be consistent with the conversions used with the CANYON-B training data to give coherent results. Added CO2SYS features do thus not add to better CANYON-B results (likely the contrary).

If this new version of CO2SYS is not backward compatible, please open an issue at the linked repository, or find ways to have two CO2SYS versions run side by side.

**Comment by simenbootsma** [comment]
Thank you for the clarification, it makes sense to keep using CO2SYS v2 in that case. I will close the issue and try to work with two different CO2SYS versions.
